[
    "Births attended by skilled health staff (% of total)",
    "Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",
    "Coverage of social insurance programs (% of population)",
    "Current health expenditure per capita (current US$)",
    "Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)",
    "Current health expenditure (% of GDP)",
    "Current health expenditure per capita (current US$)",
    "GDP (current US$)",
    "GDP per capita (current US$)",
    "Gini index (World Bank estimate)",
    "Hospital beds (per 1,000 people)",
    "Life expectancy at birth, total (years)",
    "Literacy rate, adult total (% of people ages 15 and above)",
    "Nurses and midwives (per 1,000 people)",
    "People using at least basic drinking water services (% of population)",
    "People using at least basic sanitation services (% of population)",
    "People with basic handwashing facilities including soap and water (% of population)",
    "Physicians (per 1,000 people)",
    "Population ages 65 and above (% of total population)",
    "Population density (people per sq. km of land area)",
    "Population living in slums (% of urban population)",
    "Smoking prevalence, total (ages 15+)",
    "Urban population (% of total population)"
]